name: From Above
favicon: null
typography_spectrum: 0.46216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#fdfeff'
    - '#df2e18'
    - '#d38521'
    - '#49e6f6'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
