typography_spectrum: 0.46216
color:
  brandColors:
    - '#010103'
    - '#fdfeff'
    - '#df2e18'
    - '#d38521'
    - '#49e6f6'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2027
analytics:
  google: null
  facebook: null
  twitter: null
name: From Above
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Photos taken from above
purpose: []
