name: From Above
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#fdfeff'
    - '#df2e18'
    - '#d38521'
    - '#49e6f6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
